package.path = "plugins/sudoku.koplugin/?.lua;" .. package.path

local bit = require("bit")
local flags = require("core.techniques.flags")

describe("core.techniques.flags", function()
    it("assigns bit positions per difficulty tier", function()
        assert.are.equal(1, flags.NAKED_SINGLES)
        assert.are.equal(2, flags.HIDDEN_SINGLES)
        assert.are.equal(bit.lshift(1, 8), flags.NAKED_PAIRS)
        assert.are.equal(bit.lshift(1, 9), flags.HIDDEN_PAIRS)
        assert.are.equal(bit.lshift(1, 10), flags.LOCKED_CANDIDATES)
        assert.are.equal(bit.lshift(1, 11), flags.NAKED_TRIPLES)
        assert.are.equal(bit.lshift(1, 12), flags.HIDDEN_TRIPLES)
        assert.are.equal(bit.lshift(1, 16), flags.X_WING)
        assert.are.equal(bit.lshift(1, 17), flags.NAKED_QUADS)
        assert.are.equal(bit.lshift(1, 18), flags.HIDDEN_QUADS)
        assert.are.equal(bit.lshift(1, 19), flags.SWORDFISH)
        assert.are.equal(bit.lshift(1, 20), flags.JELLYFISH)
        assert.are.equal(bit.lshift(1, 21), flags.SKYSCRAPER)
        assert.are.equal(bit.lshift(1, 24), flags.W_WING)
        assert.are.equal(bit.lshift(1, 25), flags.XY_WING)
        assert.are.equal(bit.lshift(1, 26), flags.XYZ_WING)
        assert.are.equal(bit.lshift(1, 27), flags.ALTERNATING_INFERENCE_CHAIN)
    end)

    it("provides composite tier masks", function()
        assert.are.equal(0xFF, flags.EASY)
        assert.are.equal(0xFF00, flags.MEDIUM)
        assert.are.equal(0xFF0000, flags.HARD)
        assert.are.equal(bit.tobit(0xFF000000), flags.EXPERT)
    end)

    it("counts set bits", function()
        assert.are.equal(0, flags.count(0))
        assert.are.equal(1, flags.count(flags.NAKED_SINGLES))
        assert.are.equal(3, flags.count(bit.bor(flags.NAKED_SINGLES, flags.HIDDEN_SINGLES, flags.NAKED_PAIRS)))
        assert.are.equal(8, flags.count(flags.EASY))
        assert.are.equal(8, flags.count(flags.MEDIUM))
        assert.are.equal(8, flags.count(flags.HARD))
        assert.are.equal(8, flags.count(flags.EXPERT))
    end)

    it("finds the lowest set bit index", function()
        assert.is_nil(flags.lowest_bit(0))
        assert.are.equal(0, flags.lowest_bit(flags.NAKED_SINGLES))
        assert.are.equal(1, flags.lowest_bit(flags.HIDDEN_SINGLES))
        assert.are.equal(8, flags.lowest_bit(flags.NAKED_PAIRS))
        assert.are.equal(27, flags.lowest_bit(flags.ALTERNATING_INFERENCE_CHAIN))
    end)

    it("maps flags to difficulty tiers", function()
        assert.are.equal("easy", flags.difficulty(flags.NAKED_SINGLES))
        assert.are.equal("easy", flags.difficulty(flags.HIDDEN_SINGLES))
        assert.are.equal("medium", flags.difficulty(flags.NAKED_PAIRS))
        assert.are.equal("medium", flags.difficulty(flags.LOCKED_CANDIDATES))
        assert.are.equal("hard", flags.difficulty(flags.X_WING))
        assert.are.equal("hard", flags.difficulty(flags.SKYSCRAPER))
        assert.are.equal("expert", flags.difficulty(flags.W_WING))
        assert.are.equal("expert", flags.difficulty(flags.ALTERNATING_INFERENCE_CHAIN))
        assert.are.equal("easy", flags.difficulty(0))
    end)

    it("computes difficulty points (lowest bit + 1)", function()
        assert.are.equal(0, flags.difficulty_point(0))
        assert.are.equal(1, flags.difficulty_point(flags.NAKED_SINGLES))
        assert.are.equal(2, flags.difficulty_point(flags.HIDDEN_SINGLES))
        assert.are.equal(9, flags.difficulty_point(flags.NAKED_PAIRS))
        assert.are.equal(17, flags.difficulty_point(flags.X_WING))
        assert.are.equal(28, flags.difficulty_point(flags.ALTERNATING_INFERENCE_CHAIN))
    end)
end)
